package com.meetback.dev.domain;

public enum MeetingEventType {
    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    PARTICIPANT_KICKED,
    PARTICIPANT_KICK_CANCELED,

    LOCATION_SUBMITTED,
    LOCATION_EDITING,
    LOCATION_EDIT_CANCELED,
    ALL_LOCATIONS_SUBMITTED,

    VOTING_STARTED,
    VOTE_UPDATED,
    VOTE_COMPLETED,

    MEETING_CONFIRMED
}
