package com.meetback.dev.domain;

public enum MeetingEventType {
    CHAT_MESSAGE,
    PRESENCE_UPDATED,
    QUICK_MEETING_LIST_CHANGED,
    RECRUITMENT_CLOSED,

    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    PARTICIPANT_KICKED,
    PARTICIPANT_KICK_CANCELED,

    LOCATION_SUBMITTED,
    LOCATION_EDITING,
    LOCATION_EDIT_CANCELED,
    ALL_LOCATIONS_SUBMITTED,

    VOTING_STARTED,
    VOTE_UPDATED,
    ALL_VOTES_COMPLETED,

    MEETING_CONFIRMED
}
